export const documentacaoRuralBrasilEnumerators = {
  situacaoDocumental: {
    naoInformado: 'naoInformado',
    emLevantamento: 'emLevantamento',
    pendencias: 'pendencias',
    regular: 'regular',
    emRegularizacao: 'emRegularizacao',
    bloqueado: 'bloqueado',
  },
  ccirSituacao: {
    naoInformado: 'naoInformado',
    regular: 'regular',
    pendente: 'pendente',
    vencido: 'vencido',
    inconsistente: 'inconsistente',
  },
  cafirSituacao: {
    naoInformado: 'naoInformado',
    ativo: 'ativo',
    pendente: 'pendente',
    suspenso: 'suspenso',
    cancelado: 'cancelado',
  },
  cndImovelRuralSituacao: {
    naoInformado: 'naoInformado',
    negativa: 'negativa',
    positivaComEfeitosDeNegativa: 'positivaComEfeitosDeNegativa',
    positiva: 'positiva',
    vencida: 'vencida',
  },
  carSituacao: {
    naoInformado: 'naoInformado',
    ativo: 'ativo',
    aguardandoAnalise: 'aguardandoAnalise',
    analisadoSemPendencia: 'analisadoSemPendencia',
    analisadoComPendencia: 'analisadoComPendencia',
    suspenso: 'suspenso',
    cancelado: 'cancelado',
  },
  praSituacao: {
    naoAplicavel: 'naoAplicavel',
    naoInformado: 'naoInformado',
    naoAderiu: 'naoAderiu',
    emRegularizacao: 'emRegularizacao',
    regularizado: 'regularizado',
    pendente: 'pendente',
  },
  sigefSituacao: {
    naoInformado: 'naoInformado',
    naoCertificado: 'naoCertificado',
    emAnalise: 'emAnalise',
    certificado: 'certificado',
    cancelado: 'cancelado',
    sobreposicaoOuPendencia: 'sobreposicaoOuPendencia',
  },
  licenciamentoAmbientalSituacao: {
    naoAplicavel: 'naoAplicavel',
    naoInformado: 'naoInformado',
    dispensado: 'dispensado',
    regular: 'regular',
    emRenovacao: 'emRenovacao',
    pendente: 'pendente',
    vencido: 'vencido',
  },
  outorgaAguaSituacao: {
    naoAplicavel: 'naoAplicavel',
    naoInformado: 'naoInformado',
    dispensada: 'dispensada',
    regular: 'regular',
    emRenovacao: 'emRenovacao',
    pendente: 'pendente',
    vencida: 'vencida',
  },
};
