export const benfeitoriaRuralEnumerators = {
  tipo: {
    casaSede: 'casaSede',
    casaFuncionario: 'casaFuncionario',
    alojamento: 'alojamento',
    galpao: 'galpao',
    deposito: 'deposito',
    oficina: 'oficina',
    curral: 'curral',
    brete: 'brete',
    embarcadouro: 'embarcadouro',
    balanca: 'balanca',
    silo: 'silo',
    secador: 'secador',
    armazem: 'armazem',
    estabulo: 'estabulo',
    cercas: 'cercas',
    outro: 'outro',
  },
  estadoConservacao: {
    naoInformado: 'naoInformado',
    excelente: 'excelente',
    bom: 'bom',
    regular: 'regular',
    ruim: 'ruim',
    inutilizavel: 'inutilizavel',
  },
  moeda: {
    BRL: 'BRL',
    USD: 'USD',
    PYG: 'PYG',
    ARS: 'ARS',
  },
};
