import { Hono } from 'hono';
import { authRoutes } from './auth/authApiRoutes';
import { userRoutes } from './user/userApiRoutes';
import { fileRoutes } from './file/fileApiRoutes';
import { auditLogRoutes } from './auditLog/auditLogApiRoutes';
import { filialRoutes } from './filial/filialApiRoutes';
import { corretorRoutes } from './corretor/corretorApiRoutes';
import { proprietarioRoutes } from './proprietario/proprietarioApiRoutes';
import { clienteRoutes } from './cliente/clienteApiRoutes';
import { condominioRoutes } from './condominio/condominioApiRoutes';
import { empreendimentoRoutes } from './empreendimento/empreendimentoApiRoutes';
import { imovelRoutes } from './imovel/imovelApiRoutes';
import { caracteristicaImovelRoutes } from './caracteristicaImovel/caracteristicaImovelApiRoutes';
import { imovelCaracteristicaRoutes } from './imovelCaracteristica/imovelCaracteristicaApiRoutes';
import { midiaImovelRoutes } from './midiaImovel/midiaImovelApiRoutes';
import { documentoImovelRoutes } from './documentoImovel/documentoImovelApiRoutes';
import { captacaoImovelRoutes } from './captacaoImovel/captacaoImovelApiRoutes';
import { avaliacaoImovelRoutes } from './avaliacaoImovel/avaliacaoImovelApiRoutes';
import { chaveImovelRoutes } from './chaveImovel/chaveImovelApiRoutes';
import { vistoriaRoutes } from './vistoria/vistoriaApiRoutes';
import { itemVistoriaRoutes } from './itemVistoria/itemVistoriaApiRoutes';
import { anuncioRoutes } from './anuncio/anuncioApiRoutes';
import { portalImobiliarioRoutes } from './portalImobiliario/portalImobiliarioApiRoutes';
import { publicacaoPortalRoutes } from './publicacaoPortal/publicacaoPortalApiRoutes';
import { campanhaMarketingRoutes } from './campanhaMarketing/campanhaMarketingApiRoutes';
import { campanhaAnuncioRoutes } from './campanhaAnuncio/campanhaAnuncioApiRoutes';
import { leadRoutes } from './lead/leadApiRoutes';
import { interacaoLeadRoutes } from './interacaoLead/interacaoLeadApiRoutes';
import { tarefaComercialRoutes } from './tarefaComercial/tarefaComercialApiRoutes';
import { visitaRoutes } from './visita/visitaApiRoutes';
import { propostaRoutes } from './proposta/propostaApiRoutes';
import { condicaoPropostaRoutes } from './condicaoProposta/condicaoPropostaApiRoutes';
import { reservaImovelRoutes } from './reservaImovel/reservaImovelApiRoutes';
import { vendaRoutes } from './venda/vendaApiRoutes';
import { contratoVendaRoutes } from './contratoVenda/contratoVendaApiRoutes';
import { parcelaVendaRoutes } from './parcelaVenda/parcelaVendaApiRoutes';
import { locacaoRoutes } from './locacao/locacaoApiRoutes';
import { participanteLocacaoRoutes } from './participanteLocacao/participanteLocacaoApiRoutes';
import { garantiaLocacaoRoutes } from './garantiaLocacao/garantiaLocacaoApiRoutes';
import { contratoLocacaoRoutes } from './contratoLocacao/contratoLocacaoApiRoutes';
import { cobrancaLocacaoRoutes } from './cobrancaLocacao/cobrancaLocacaoApiRoutes';
import { pagamentoLocacaoRoutes } from './pagamentoLocacao/pagamentoLocacaoApiRoutes';
import { reajusteLocacaoRoutes } from './reajusteLocacao/reajusteLocacaoApiRoutes';
import { repasseProprietarioRoutes } from './repasseProprietario/repasseProprietarioApiRoutes';
import { comissaoRoutes } from './comissao/comissaoApiRoutes';
import { pagamentoComissaoRoutes } from './pagamentoComissao/pagamentoComissaoApiRoutes';
import { fornecedorRoutes } from './fornecedor/fornecedorApiRoutes';
import { solicitacaoManutencaoRoutes } from './solicitacaoManutencao/solicitacaoManutencaoApiRoutes';
import { ordemServicoRoutes } from './ordemServico/ordemServicoApiRoutes';
import { despesaImovelRoutes } from './despesaImovel/despesaImovelApiRoutes';
import { contaFinanceiraRoutes } from './contaFinanceira/contaFinanceiraApiRoutes';
import { categoriaFinanceiraRoutes } from './categoriaFinanceira/categoriaFinanceiraApiRoutes';
import { lancamentoFinanceiroRoutes } from './lancamentoFinanceiro/lancamentoFinanceiroApiRoutes';
import { documentoPessoaRoutes } from './documentoPessoa/documentoPessoaApiRoutes';
import { consentimentoLGPDRoutes } from './consentimentoLGPD/consentimentoLGPDApiRoutes';
import { favoritoClienteRoutes } from './favoritoCliente/favoritoClienteApiRoutes';
import { solicitacaoContatoRoutes } from './solicitacaoContato/solicitacaoContatoApiRoutes';
import { simulacaoFinanciamentoRoutes } from './simulacaoFinanciamento/simulacaoFinanciamentoApiRoutes';
import { contratoAdministracaoRoutes } from './contratoAdministracao/contratoAdministracaoApiRoutes';
import { seguroImovelRoutes } from './seguroImovel/seguroImovelApiRoutes';
import { ocorrenciaImovelRoutes } from './ocorrenciaImovel/ocorrenciaImovelApiRoutes';
import { arquivoKmlRoutes } from './arquivoKml/arquivoKmlApiRoutes';
import { documentacaoRuralBrasilRoutes } from './documentacaoRuralBrasil/documentacaoRuralBrasilApiRoutes';
import { referenciaClimaticaRuralRoutes } from './referenciaClimaticaRural/referenciaClimaticaRuralApiRoutes';
import { tipoSoloRoutes } from './tipoSolo/tipoSoloApiRoutes';
import { soloImovelRuralRoutes } from './soloImovelRural/soloImovelRuralApiRoutes';
import { topografiaRuralRoutes } from './topografiaRural/topografiaRuralApiRoutes';
import { recursoHidricoRuralRoutes } from './recursoHidricoRural/recursoHidricoRuralApiRoutes';
import { infraestruturaEnergiaConectividadeRoutes } from './infraestruturaEnergiaConectividade/infraestruturaEnergiaConectividadeApiRoutes';
import { logisticaRuralRoutes } from './logisticaRural/logisticaRuralApiRoutes';
import { pistaAviacaoRuralRoutes } from './pistaAviacaoRural/pistaAviacaoRuralApiRoutes';
import { benfeitoriaRuralRoutes } from './benfeitoriaRural/benfeitoriaRuralApiRoutes';
import { divisaoOperacionalRuralRoutes } from './divisaoOperacionalRural/divisaoOperacionalRuralApiRoutes';
import { producaoHistoricaRuralRoutes } from './producaoHistoricaRural/producaoHistoricaRuralApiRoutes';
import { sistemaProdutivoRuralRoutes } from './sistemaProdutivoRural/sistemaProdutivoRuralApiRoutes';
import { ativoIncluidoVendaRuralRoutes } from './ativoIncluidoVendaRural/ativoIncluidoVendaRuralApiRoutes';
import { restricaoTerritorialRuralRoutes } from './restricaoTerritorialRural/restricaoTerritorialRuralApiRoutes';
import { riscoRuralRoutes } from './riscoRural/riscoRuralApiRoutes';
import { certificacaoSustentabilidadeRuralRoutes } from './certificacaoSustentabilidadeRural/certificacaoSustentabilidadeRuralApiRoutes';
import { condicaoComercialRuralRoutes } from './condicaoComercialRural/condicaoComercialRuralApiRoutes';
import { dueDiligenceRuralRoutes } from './dueDiligenceRural/dueDiligenceRuralApiRoutes';
import { paisRoutes } from './pais/paisApiRoutes';
import { estadoRoutes } from './estado/estadoApiRoutes';
import { cidadeRoutes } from './cidade/cidadeApiRoutes';
import { subscriptionRoutes } from './subscription/subscriptionApiRoutes';
import { apiDocsRoutes } from './apiDocs/apiDocsApiRoutes';
import { configRoutes } from './config/configRoutes';
import { memberRoutes } from './member/memberApiRoutes';
import { invitationRoutes } from './invitation/invitationRoutes';
import { apiKeyRoutes } from './apiKey/apiKeyApiRoutes';
import { organizationRoutes } from './organization/organizationApiRoutes';
import { chatbotRoutes } from './chatbot/chatbotApiRoutes';
import { pushTokenRoutes } from './pushToken/pushTokenApiRoutes';
import { notificationRoutes } from './notification/notificationApiRoutes';
import { backgroundJobsRoutes } from './backgroundJobs/backgroundJobsApiRoutes';
import mcpRoutes from './mcp/mcp';
import { publicHomeRoutes } from './publicHome/publicHomeApiRoutes';

export const apiRoutes = new Hono();

apiRoutes.get('/health', (c) => c.json({ status: 'ok' }));
apiRoutes.route('/api-docs', apiDocsRoutes);
apiRoutes.route('/config', configRoutes);
apiRoutes.route('/public', publicHomeRoutes);
apiRoutes.route('/auth', authRoutes);
apiRoutes.route('/user', userRoutes);
apiRoutes.route('/organization', organizationRoutes);
apiRoutes.route('/member/invitation', invitationRoutes);
apiRoutes.route('/member', memberRoutes);
apiRoutes.route('/file', fileRoutes);
apiRoutes.route('/audit-log', auditLogRoutes);
apiRoutes.route('/filial', filialRoutes);
apiRoutes.route('/corretor', corretorRoutes);
apiRoutes.route('/proprietario', proprietarioRoutes);
apiRoutes.route('/cliente', clienteRoutes);
apiRoutes.route('/condominio', condominioRoutes);
apiRoutes.route('/empreendimento', empreendimentoRoutes);
apiRoutes.route('/imovel', imovelRoutes);
apiRoutes.route('/caracteristica-imovel', caracteristicaImovelRoutes);
apiRoutes.route('/imovel-caracteristica', imovelCaracteristicaRoutes);
apiRoutes.route('/midia-imovel', midiaImovelRoutes);
apiRoutes.route('/documento-imovel', documentoImovelRoutes);
apiRoutes.route('/captacao-imovel', captacaoImovelRoutes);
apiRoutes.route('/avaliacao-imovel', avaliacaoImovelRoutes);
apiRoutes.route('/chave-imovel', chaveImovelRoutes);
apiRoutes.route('/vistoria', vistoriaRoutes);
apiRoutes.route('/item-vistoria', itemVistoriaRoutes);
apiRoutes.route('/anuncio', anuncioRoutes);
apiRoutes.route('/portal-imobiliario', portalImobiliarioRoutes);
apiRoutes.route('/publicacao-portal', publicacaoPortalRoutes);
apiRoutes.route('/campanha-marketing', campanhaMarketingRoutes);
apiRoutes.route('/campanha-anuncio', campanhaAnuncioRoutes);
apiRoutes.route('/lead', leadRoutes);
apiRoutes.route('/interacao-lead', interacaoLeadRoutes);
apiRoutes.route('/tarefa-comercial', tarefaComercialRoutes);
apiRoutes.route('/visita', visitaRoutes);
apiRoutes.route('/proposta', propostaRoutes);
apiRoutes.route('/condicao-proposta', condicaoPropostaRoutes);
apiRoutes.route('/reserva-imovel', reservaImovelRoutes);
apiRoutes.route('/venda', vendaRoutes);
apiRoutes.route('/contrato-venda', contratoVendaRoutes);
apiRoutes.route('/parcela-venda', parcelaVendaRoutes);
apiRoutes.route('/locacao', locacaoRoutes);
apiRoutes.route('/participante-locacao', participanteLocacaoRoutes);
apiRoutes.route('/garantia-locacao', garantiaLocacaoRoutes);
apiRoutes.route('/contrato-locacao', contratoLocacaoRoutes);
apiRoutes.route('/cobranca-locacao', cobrancaLocacaoRoutes);
apiRoutes.route('/pagamento-locacao', pagamentoLocacaoRoutes);
apiRoutes.route('/reajuste-locacao', reajusteLocacaoRoutes);
apiRoutes.route('/repasse-proprietario', repasseProprietarioRoutes);
apiRoutes.route('/comissao', comissaoRoutes);
apiRoutes.route('/pagamento-comissao', pagamentoComissaoRoutes);
apiRoutes.route('/fornecedor', fornecedorRoutes);
apiRoutes.route('/solicitacao-manutencao', solicitacaoManutencaoRoutes);
apiRoutes.route('/ordem-servico', ordemServicoRoutes);
apiRoutes.route('/despesa-imovel', despesaImovelRoutes);
apiRoutes.route('/conta-financeira', contaFinanceiraRoutes);
apiRoutes.route('/categoria-financeira', categoriaFinanceiraRoutes);
apiRoutes.route('/lancamento-financeiro', lancamentoFinanceiroRoutes);
apiRoutes.route('/documento-pessoa', documentoPessoaRoutes);
apiRoutes.route('/consentimento-l-g-p-d', consentimentoLGPDRoutes);
apiRoutes.route('/favorito-cliente', favoritoClienteRoutes);
apiRoutes.route('/solicitacao-contato', solicitacaoContatoRoutes);
apiRoutes.route('/simulacao-financiamento', simulacaoFinanciamentoRoutes);
apiRoutes.route('/contrato-administracao', contratoAdministracaoRoutes);
apiRoutes.route('/seguro-imovel', seguroImovelRoutes);
apiRoutes.route('/ocorrencia-imovel', ocorrenciaImovelRoutes);
apiRoutes.route('/arquivo-kml', arquivoKmlRoutes);
apiRoutes.route('/documentacao-rural-brasil', documentacaoRuralBrasilRoutes);
apiRoutes.route('/referencia-climatica-rural', referenciaClimaticaRuralRoutes);
apiRoutes.route('/tipo-solo', tipoSoloRoutes);
apiRoutes.route('/solo-imovel-rural', soloImovelRuralRoutes);
apiRoutes.route('/topografia-rural', topografiaRuralRoutes);
apiRoutes.route('/recurso-hidrico-rural', recursoHidricoRuralRoutes);
apiRoutes.route(
  '/infraestrutura-energia-conectividade',
  infraestruturaEnergiaConectividadeRoutes,
);
apiRoutes.route('/logistica-rural', logisticaRuralRoutes);
apiRoutes.route('/pista-aviacao-rural', pistaAviacaoRuralRoutes);
apiRoutes.route('/benfeitoria-rural', benfeitoriaRuralRoutes);
apiRoutes.route('/divisao-operacional-rural', divisaoOperacionalRuralRoutes);
apiRoutes.route('/producao-historica-rural', producaoHistoricaRuralRoutes);
apiRoutes.route('/sistema-produtivo-rural', sistemaProdutivoRuralRoutes);
apiRoutes.route('/ativo-incluido-venda-rural', ativoIncluidoVendaRuralRoutes);
apiRoutes.route(
  '/restricao-territorial-rural',
  restricaoTerritorialRuralRoutes,
);
apiRoutes.route('/risco-rural', riscoRuralRoutes);
apiRoutes.route(
  '/certificacao-sustentabilidade-rural',
  certificacaoSustentabilidadeRuralRoutes,
);
apiRoutes.route('/condicao-comercial-rural', condicaoComercialRuralRoutes);
apiRoutes.route('/due-diligence-rural', dueDiligenceRuralRoutes);
apiRoutes.route('/pais', paisRoutes);
apiRoutes.route('/estado', estadoRoutes);
apiRoutes.route('/cidade', cidadeRoutes);
apiRoutes.route('/subscription', subscriptionRoutes);
apiRoutes.route('/api-key', apiKeyRoutes);
apiRoutes.route('/chatbot', chatbotRoutes);
apiRoutes.route('/push-token', pushTokenRoutes);
apiRoutes.route('/notification', notificationRoutes);
apiRoutes.route('/background-jobs', backgroundJobsRoutes);

// MCP server endpoint
apiRoutes.route('/mcp', mcpRoutes);
