import { createAccessControl } from 'better-auth/plugins/access';

export interface StorageConfig {
  readonly id: string;
  readonly folder: string;
  readonly maxSizeInBytes: number;
  readonly publicRead?: boolean;
  readonly fileTypes?: string[];
  readonly roles: Array<keyof typeof rolesIds>;
}

type StorageRecord = Record<string, StorageConfig>;

function validateStorageKeys<T extends StorageRecord>(
  config: T & {
    [K in keyof T]: T[K] extends { id: infer ID }
      ? ID extends K
        ? T[K]
        : never
      : never;
  },
): T {
  return config;
}

export const accessControlStatement = {
  organization: ['read', 'update', 'delete'],
  member: [
    'create',
    'update',
    'delete',
    'read',
    'autocomplete',
    'import',
    'export',
  ],
  invitation: ['create', 'read', 'resend', 'cancel', 'export'],
  apiDocs: ['read'],
  apiKey: ['create', 'read', 'update', 'delete'],
  subscription: ['read', 'create', 'update'],
  auditLog: ['read', 'export'],
  chatbot: ['use'],
  mcp: ['use'],
  notification: ['read', 'create'],
  memberSession: ['read', 'revoke'],
  filial: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  corretor: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  proprietario: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  cliente: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  condominio: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  empreendimento: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  imovel: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  caracteristicaImovel: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  imovelCaracteristica: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  midiaImovel: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  documentoImovel: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  captacaoImovel: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  avaliacaoImovel: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  chaveImovel: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  vistoria: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  itemVistoria: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  anuncio: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  portalImobiliario: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  publicacaoPortal: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  campanhaMarketing: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  campanhaAnuncio: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  lead: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  interacaoLead: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  tarefaComercial: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  visita: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  proposta: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  condicaoProposta: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  reservaImovel: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  venda: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  contratoVenda: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  parcelaVenda: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  locacao: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  participanteLocacao: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  garantiaLocacao: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  contratoLocacao: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  cobrancaLocacao: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  pagamentoLocacao: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  reajusteLocacao: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  repasseProprietario: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  comissao: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  pagamentoComissao: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  fornecedor: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  solicitacaoManutencao: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  ordemServico: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  despesaImovel: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  contaFinanceira: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  categoriaFinanceira: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  lancamentoFinanceiro: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  documentoPessoa: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  consentimentoLGPD: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  favoritoCliente: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  solicitacaoContato: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  simulacaoFinanciamento: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  contratoAdministracao: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  seguroImovel: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  ocorrenciaImovel: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  arquivoKml: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  documentacaoRuralBrasil: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  referenciaClimaticaRural: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  tipoSolo: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  soloImovelRural: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  topografiaRural: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  recursoHidricoRural: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  infraestruturaEnergiaConectividade: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  logisticaRural: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  pistaAviacaoRural: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  benfeitoriaRural: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  divisaoOperacionalRural: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  producaoHistoricaRural: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  sistemaProdutivoRural: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  ativoIncluidoVendaRural: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  restricaoTerritorialRural: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  riscoRural: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  certificacaoSustentabilidadeRural: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  condicaoComercialRural: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  dueDiligenceRural: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  pais: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  estado: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  cidade: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
} as const;

export const accessControl = createAccessControl(accessControlStatement);

type Statements = typeof accessControl.statements;

export type PartialPermissions = {
  [K in keyof Statements]?: Statements[K] extends readonly (infer U)[]
    ? U[]
    : never;
};

const admin = accessControl.newRole({
  organization: ['read', 'update', 'delete'],
  member: [
    'create',
    'update',
    'delete',
    'read',
    'autocomplete',
    'import',
    'export',
  ],
  invitation: ['create', 'read', 'resend', 'cancel', 'export'],
  apiDocs: ['read'],
  apiKey: ['create', 'read', 'update', 'delete'],
  subscription: ['read', 'create', 'update'],
  auditLog: ['read', 'export'],
  chatbot: ['use'],
  mcp: ['use'],
  notification: ['read', 'create'],
  memberSession: ['read', 'revoke'],
  filial: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  corretor: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  proprietario: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  cliente: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  condominio: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  empreendimento: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  imovel: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  caracteristicaImovel: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  imovelCaracteristica: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  midiaImovel: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  documentoImovel: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  captacaoImovel: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  avaliacaoImovel: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  chaveImovel: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  vistoria: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  itemVistoria: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  anuncio: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  portalImobiliario: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  publicacaoPortal: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  campanhaMarketing: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  campanhaAnuncio: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  lead: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  interacaoLead: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  tarefaComercial: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  visita: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  proposta: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  condicaoProposta: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  reservaImovel: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  venda: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  contratoVenda: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  parcelaVenda: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  locacao: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  participanteLocacao: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  garantiaLocacao: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  contratoLocacao: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  cobrancaLocacao: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  pagamentoLocacao: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  reajusteLocacao: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  repasseProprietario: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  comissao: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  pagamentoComissao: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  fornecedor: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  solicitacaoManutencao: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  ordemServico: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  despesaImovel: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  contaFinanceira: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  categoriaFinanceira: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  lancamentoFinanceiro: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  documentoPessoa: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  consentimentoLGPD: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  favoritoCliente: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  solicitacaoContato: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  simulacaoFinanciamento: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  contratoAdministracao: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  seguroImovel: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  ocorrenciaImovel: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  arquivoKml: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  documentacaoRuralBrasil: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  referenciaClimaticaRural: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  tipoSolo: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  soloImovelRural: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  topografiaRural: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  recursoHidricoRural: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  infraestruturaEnergiaConectividade: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  logisticaRural: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  pistaAviacaoRural: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  benfeitoriaRural: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  divisaoOperacionalRural: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  producaoHistoricaRural: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  sistemaProdutivoRural: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  ativoIncluidoVendaRural: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  restricaoTerritorialRural: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  riscoRural: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  certificacaoSustentabilidadeRural: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  condicaoComercialRural: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  dueDiligenceRural: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  pais: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  estado: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  cidade: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
});

const member = accessControl.newRole({
  member: ['autocomplete'],
  subscription: ['read', 'create', 'update'],
  chatbot: ['use'],
  mcp: ['use'],
  notification: ['read'],
  filial: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  corretor: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  proprietario: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  cliente: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  condominio: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  empreendimento: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  imovel: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  caracteristicaImovel: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  imovelCaracteristica: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  midiaImovel: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  documentoImovel: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  captacaoImovel: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  avaliacaoImovel: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  chaveImovel: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  vistoria: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  itemVistoria: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  anuncio: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  portalImobiliario: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  publicacaoPortal: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  campanhaMarketing: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  campanhaAnuncio: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  lead: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  interacaoLead: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  tarefaComercial: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  visita: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  proposta: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  condicaoProposta: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  reservaImovel: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  venda: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  contratoVenda: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  parcelaVenda: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  locacao: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  participanteLocacao: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  garantiaLocacao: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  contratoLocacao: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  cobrancaLocacao: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  pagamentoLocacao: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  reajusteLocacao: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  repasseProprietario: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  comissao: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  pagamentoComissao: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  fornecedor: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  solicitacaoManutencao: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  ordemServico: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  despesaImovel: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  contaFinanceira: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  categoriaFinanceira: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  lancamentoFinanceiro: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  documentoPessoa: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  consentimentoLGPD: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  favoritoCliente: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  solicitacaoContato: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  simulacaoFinanciamento: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  contratoAdministracao: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  seguroImovel: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  ocorrenciaImovel: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  arquivoKml: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  documentacaoRuralBrasil: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  referenciaClimaticaRural: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  tipoSolo: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  soloImovelRural: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  topografiaRural: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  recursoHidricoRural: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  infraestruturaEnergiaConectividade: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  logisticaRural: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  pistaAviacaoRural: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  benfeitoriaRural: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  divisaoOperacionalRural: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  producaoHistoricaRural: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  sistemaProdutivoRural: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  ativoIncluidoVendaRural: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  restricaoTerritorialRural: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  riscoRural: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  certificacaoSustentabilidadeRural: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  condicaoComercialRural: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  dueDiligenceRural: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  pais: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  estado: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
  cidade: [
    'import',
    'create',
    'update',
    'read',
    'autocomplete',
    'delete',
    'archive',
    'restore',
    'export',
  ],
});

export const roles = {
  admin,
  member,
} as const;

export const rolesIds = { admin: 'admin', member: 'member' } as const;

export const storage = validateStorageKeys({
  memberAvatars: {
    id: 'memberAvatars',
    folder: 'organization/:organizationId/member/avatars',
    maxSizeInBytes: 10_000_000,
    publicRead: true,
    fileTypes: ['image/*'],
    roles: [rolesIds.admin, rolesIds.member],
  },
  organizationLogos: {
    id: 'organizationLogos',
    folder: 'organization/:organizationId/logos',
    maxSizeInBytes: 5_000_000,
    publicRead: true,
    fileTypes: ['image/*'],
    roles: [rolesIds.admin],
  },
  corretorFoto: {
    id: 'corretorFoto',
    folder: 'organization/:organizationId/corretor/foto',
    maxSizeInBytes: 100_000_000,
    fileTypes: ['image/*'],
    roles: [rolesIds.admin],
  },
  empreendimentoDocumentos: {
    id: 'empreendimentoDocumentos',
    folder: 'organization/:organizationId/empreendimento/documentos',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  empreendimentoImagens: {
    id: 'empreendimentoImagens',
    folder: 'organization/:organizationId/empreendimento/imagens',
    maxSizeInBytes: 100_000_000,
    fileTypes: ['image/*'],
    roles: [rolesIds.admin],
  },
  imovelMapaUsoAlternativo: {
    id: 'imovelMapaUsoAlternativo',
    folder: 'organization/:organizationId/imovel/mapaUsoAlternativo',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  midiaImovelImagens: {
    id: 'midiaImovelImagens',
    folder: 'organization/:organizationId/midiaImovel/imagens',
    maxSizeInBytes: 100_000_000,
    fileTypes: ['image/*'],
    roles: [rolesIds.admin],
  },
  documentoImovelArquivos: {
    id: 'documentoImovelArquivos',
    folder: 'organization/:organizationId/documentoImovel/arquivos',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  captacaoImovelDocumentos: {
    id: 'captacaoImovelDocumentos',
    folder: 'organization/:organizationId/captacaoImovel/documentos',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  avaliacaoImovelLaudo: {
    id: 'avaliacaoImovelLaudo',
    folder: 'organization/:organizationId/avaliacaoImovel/laudo',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  vistoriaAssinaturaResponsavel: {
    id: 'vistoriaAssinaturaResponsavel',
    folder: 'organization/:organizationId/vistoria/assinaturaResponsavel',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  itemVistoriaFotos: {
    id: 'itemVistoriaFotos',
    folder: 'organization/:organizationId/itemVistoria/fotos',
    maxSizeInBytes: 100_000_000,
    fileTypes: ['image/*'],
    roles: [rolesIds.admin],
  },
  propostaDocumentos: {
    id: 'propostaDocumentos',
    folder: 'organization/:organizationId/proposta/documentos',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  reservaImovelComprovante: {
    id: 'reservaImovelComprovante',
    folder: 'organization/:organizationId/reservaImovel/comprovante',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  contratoVendaArquivos: {
    id: 'contratoVendaArquivos',
    folder: 'organization/:organizationId/contratoVenda/arquivos',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  parcelaVendaComprovantes: {
    id: 'parcelaVendaComprovantes',
    folder: 'organization/:organizationId/parcelaVenda/comprovantes',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  garantiaLocacaoDocumentos: {
    id: 'garantiaLocacaoDocumentos',
    folder: 'organization/:organizationId/garantiaLocacao/documentos',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  contratoLocacaoArquivos: {
    id: 'contratoLocacaoArquivos',
    folder: 'organization/:organizationId/contratoLocacao/arquivos',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  pagamentoLocacaoComprovantes: {
    id: 'pagamentoLocacaoComprovantes',
    folder: 'organization/:organizationId/pagamentoLocacao/comprovantes',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  reajusteLocacaoDocumentos: {
    id: 'reajusteLocacaoDocumentos',
    folder: 'organization/:organizationId/reajusteLocacao/documentos',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  repasseProprietarioComprovante: {
    id: 'repasseProprietarioComprovante',
    folder: 'organization/:organizationId/repasseProprietario/comprovante',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  pagamentoComissaoComprovante: {
    id: 'pagamentoComissaoComprovante',
    folder: 'organization/:organizationId/pagamentoComissao/comprovante',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  solicitacaoManutencaoImagens: {
    id: 'solicitacaoManutencaoImagens',
    folder: 'organization/:organizationId/solicitacaoManutencao/imagens',
    maxSizeInBytes: 100_000_000,
    fileTypes: ['image/*'],
    roles: [rolesIds.admin],
  },
  ordemServicoDocumentos: {
    id: 'ordemServicoDocumentos',
    folder: 'organization/:organizationId/ordemServico/documentos',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  ordemServicoFotosAntes: {
    id: 'ordemServicoFotosAntes',
    folder: 'organization/:organizationId/ordemServico/fotosAntes',
    maxSizeInBytes: 100_000_000,
    fileTypes: ['image/*'],
    roles: [rolesIds.admin],
  },
  ordemServicoFotosDepois: {
    id: 'ordemServicoFotosDepois',
    folder: 'organization/:organizationId/ordemServico/fotosDepois',
    maxSizeInBytes: 100_000_000,
    fileTypes: ['image/*'],
    roles: [rolesIds.admin],
  },
  despesaImovelDocumentos: {
    id: 'despesaImovelDocumentos',
    folder: 'organization/:organizationId/despesaImovel/documentos',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  lancamentoFinanceiroDocumentos: {
    id: 'lancamentoFinanceiroDocumentos',
    folder: 'organization/:organizationId/lancamentoFinanceiro/documentos',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  documentoPessoaArquivos: {
    id: 'documentoPessoaArquivos',
    folder: 'organization/:organizationId/documentoPessoa/arquivos',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  consentimentoLGPDComprovante: {
    id: 'consentimentoLGPDComprovante',
    folder: 'organization/:organizationId/consentimentoLGPD/comprovante',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  contratoAdministracaoArquivos: {
    id: 'contratoAdministracaoArquivos',
    folder: 'organization/:organizationId/contratoAdministracao/arquivos',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  seguroImovelDocumentos: {
    id: 'seguroImovelDocumentos',
    folder: 'organization/:organizationId/seguroImovel/documentos',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  ocorrenciaImovelAnexos: {
    id: 'ocorrenciaImovelAnexos',
    folder: 'organization/:organizationId/ocorrenciaImovel/anexos',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  arquivoKmlArquivo: {
    id: 'arquivoKmlArquivo',
    folder: 'organization/:organizationId/arquivoKml/arquivo',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  documentacaoRuralBrasilMatriculaArquivo: {
    id: 'documentacaoRuralBrasilMatriculaArquivo',
    folder:
      'organization/:organizationId/documentacaoRuralBrasil/matriculaArquivo',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  documentacaoRuralBrasilCcirArquivo: {
    id: 'documentacaoRuralBrasilCcirArquivo',
    folder: 'organization/:organizationId/documentacaoRuralBrasil/ccirArquivo',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  documentacaoRuralBrasilComprovanteCafir: {
    id: 'documentacaoRuralBrasilComprovanteCafir',
    folder:
      'organization/:organizationId/documentacaoRuralBrasil/comprovanteCafir',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  documentacaoRuralBrasilDitrArquivo: {
    id: 'documentacaoRuralBrasilDitrArquivo',
    folder: 'organization/:organizationId/documentacaoRuralBrasil/ditrArquivo',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  documentacaoRuralBrasilCndImovelRuralArquivo: {
    id: 'documentacaoRuralBrasilCndImovelRuralArquivo',
    folder:
      'organization/:organizationId/documentacaoRuralBrasil/cndImovelRuralArquivo',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  documentacaoRuralBrasilCarReciboArquivo: {
    id: 'documentacaoRuralBrasilCarReciboArquivo',
    folder:
      'organization/:organizationId/documentacaoRuralBrasil/carReciboArquivo',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  documentacaoRuralBrasilCarDemonstrativoArquivo: {
    id: 'documentacaoRuralBrasilCarDemonstrativoArquivo',
    folder:
      'organization/:organizationId/documentacaoRuralBrasil/carDemonstrativoArquivo',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  documentacaoRuralBrasilTermoPraArquivo: {
    id: 'documentacaoRuralBrasilTermoPraArquivo',
    folder:
      'organization/:organizationId/documentacaoRuralBrasil/termoPraArquivo',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  documentacaoRuralBrasilSigefArquivo: {
    id: 'documentacaoRuralBrasilSigefArquivo',
    folder: 'organization/:organizationId/documentacaoRuralBrasil/sigefArquivo',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  documentacaoRuralBrasilMemorialDescritivoArquivo: {
    id: 'documentacaoRuralBrasilMemorialDescritivoArquivo',
    folder:
      'organization/:organizationId/documentacaoRuralBrasil/memorialDescritivoArquivo',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  documentacaoRuralBrasilPlantaGeorreferenciadaArquivo: {
    id: 'documentacaoRuralBrasilPlantaGeorreferenciadaArquivo',
    folder:
      'organization/:organizationId/documentacaoRuralBrasil/plantaGeorreferenciadaArquivo',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  documentacaoRuralBrasilArtRrtTrtArquivo: {
    id: 'documentacaoRuralBrasilArtRrtTrtArquivo',
    folder:
      'organization/:organizationId/documentacaoRuralBrasil/artRrtTrtArquivo',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  documentacaoRuralBrasilCertidaoOnusArquivo: {
    id: 'documentacaoRuralBrasilCertidaoOnusArquivo',
    folder:
      'organization/:organizationId/documentacaoRuralBrasil/certidaoOnusArquivo',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  documentacaoRuralBrasilCertidaoAcoesArquivo: {
    id: 'documentacaoRuralBrasilCertidaoAcoesArquivo',
    folder:
      'organization/:organizationId/documentacaoRuralBrasil/certidaoAcoesArquivo',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  documentacaoRuralBrasilTituloAquisicaoArquivo: {
    id: 'documentacaoRuralBrasilTituloAquisicaoArquivo',
    folder:
      'organization/:organizationId/documentacaoRuralBrasil/tituloAquisicaoArquivo',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  documentacaoRuralBrasilArrendamentoArquivo: {
    id: 'documentacaoRuralBrasilArrendamentoArquivo',
    folder:
      'organization/:organizationId/documentacaoRuralBrasil/arrendamentoArquivo',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  documentacaoRuralBrasilParceriaRuralArquivo: {
    id: 'documentacaoRuralBrasilParceriaRuralArquivo',
    folder:
      'organization/:organizationId/documentacaoRuralBrasil/parceriaRuralArquivo',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  documentacaoRuralBrasilLicencasAmbientaisArquivo: {
    id: 'documentacaoRuralBrasilLicencasAmbientaisArquivo',
    folder:
      'organization/:organizationId/documentacaoRuralBrasil/licencasAmbientaisArquivo',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  documentacaoRuralBrasilOutorgaAguaArquivo: {
    id: 'documentacaoRuralBrasilOutorgaAguaArquivo',
    folder:
      'organization/:organizationId/documentacaoRuralBrasil/outorgaAguaArquivo',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  referenciaClimaticaRuralMapaClimatico: {
    id: 'referenciaClimaticaRuralMapaClimatico',
    folder:
      'organization/:organizationId/referenciaClimaticaRural/mapaClimatico',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  referenciaClimaticaRuralArquivoDados: {
    id: 'referenciaClimaticaRuralArquivoDados',
    folder:
      'organization/:organizationId/referenciaClimaticaRural/arquivoDados',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  tipoSoloMapaReferencia: {
    id: 'tipoSoloMapaReferencia',
    folder: 'organization/:organizationId/tipoSolo/mapaReferencia',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  soloImovelRuralAnaliseSoloArquivo: {
    id: 'soloImovelRuralAnaliseSoloArquivo',
    folder: 'organization/:organizationId/soloImovelRural/analiseSoloArquivo',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  soloImovelRuralMapaSoloArquivo: {
    id: 'soloImovelRuralMapaSoloArquivo',
    folder: 'organization/:organizationId/soloImovelRural/mapaSoloArquivo',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  soloImovelRuralArquivoKmlSolo: {
    id: 'soloImovelRuralArquivoKmlSolo',
    folder: 'organization/:organizationId/soloImovelRural/arquivoKmlSolo',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  topografiaRuralMapaTopografico: {
    id: 'topografiaRuralMapaTopografico',
    folder: 'organization/:organizationId/topografiaRural/mapaTopografico',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  topografiaRuralArquivoDem: {
    id: 'topografiaRuralArquivoDem',
    folder: 'organization/:organizationId/topografiaRural/arquivoDem',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  recursoHidricoRuralDocumentoOutorga: {
    id: 'recursoHidricoRuralDocumentoOutorga',
    folder: 'organization/:organizationId/recursoHidricoRural/documentoOutorga',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  recursoHidricoRuralKml: {
    id: 'recursoHidricoRuralKml',
    folder: 'organization/:organizationId/recursoHidricoRural/kml',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  pistaAviacaoRuralDocumentoHabilitacao: {
    id: 'pistaAviacaoRuralDocumentoHabilitacao',
    folder:
      'organization/:organizationId/pistaAviacaoRural/documentoHabilitacao',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  pistaAviacaoRuralFotos: {
    id: 'pistaAviacaoRuralFotos',
    folder: 'organization/:organizationId/pistaAviacaoRural/fotos',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  benfeitoriaRuralFotos: {
    id: 'benfeitoriaRuralFotos',
    folder: 'organization/:organizationId/benfeitoriaRural/fotos',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  benfeitoriaRuralDocumentos: {
    id: 'benfeitoriaRuralDocumentos',
    folder: 'organization/:organizationId/benfeitoriaRural/documentos',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  divisaoOperacionalRuralKml: {
    id: 'divisaoOperacionalRuralKml',
    folder: 'organization/:organizationId/divisaoOperacionalRural/kml',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  producaoHistoricaRuralDocumentos: {
    id: 'producaoHistoricaRuralDocumentos',
    folder: 'organization/:organizationId/producaoHistoricaRural/documentos',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  ativoIncluidoVendaRuralDocumentos: {
    id: 'ativoIncluidoVendaRuralDocumentos',
    folder: 'organization/:organizationId/ativoIncluidoVendaRural/documentos',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  ativoIncluidoVendaRuralFotos: {
    id: 'ativoIncluidoVendaRuralFotos',
    folder: 'organization/:organizationId/ativoIncluidoVendaRural/fotos',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  restricaoTerritorialRuralDocumentos: {
    id: 'restricaoTerritorialRuralDocumentos',
    folder: 'organization/:organizationId/restricaoTerritorialRural/documentos',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  restricaoTerritorialRuralKml: {
    id: 'restricaoTerritorialRuralKml',
    folder: 'organization/:organizationId/restricaoTerritorialRural/kml',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  riscoRuralDocumentos: {
    id: 'riscoRuralDocumentos',
    folder: 'organization/:organizationId/riscoRural/documentos',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  certificacaoSustentabilidadeRuralDocumentos: {
    id: 'certificacaoSustentabilidadeRuralDocumentos',
    folder:
      'organization/:organizationId/certificacaoSustentabilidadeRural/documentos',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
  dueDiligenceRuralRelatorio: {
    id: 'dueDiligenceRuralRelatorio',
    folder: 'organization/:organizationId/dueDiligenceRural/relatorio',
    maxSizeInBytes: 1_000_000_000,
    roles: [rolesIds.admin],
  },
} as const);

export type StorageKey = keyof typeof storage;
export type StorageId = (typeof storage)[StorageKey]['id'];

export function hasStoragePermission(
  config: StorageConfig,
  context: { currentMember?: { role: string } | null },
): boolean {
  if (!context.currentMember) {
    return false;
  }

  return config.roles.includes(context.currentMember.role as any);
}
