export const tipoSoloEnumerators = {
  classeTextural: {
    naoInformado: 'naoInformado',
    arenoso: 'arenoso',
    francoArenoso: 'francoArenoso',
    franco: 'franco',
    francoArgiloso: 'francoArgiloso',
    argiloso: 'argiloso',
    muitoArgiloso: 'muitoArgiloso',
    siltoso: 'siltoso',
    misto: 'misto',
  },
  drenagem: {
    naoInformado: 'naoInformado',
    muitoBoa: 'muitoBoa',
    boa: 'boa',
    moderada: 'moderada',
    imperfeita: 'imperfeita',
    ruim: 'ruim',
  },
  fertilidadeNatural: {
    naoInformado: 'naoInformado',
    muitoBaixa: 'muitoBaixa',
    baixa: 'baixa',
    media: 'media',
    alta: 'alta',
    muitoAlta: 'muitoAlta',
  },
  materiaOrganica: {
    naoInformado: 'naoInformado',
    muitoBaixa: 'muitoBaixa',
    baixa: 'baixa',
    media: 'media',
    alta: 'alta',
    muitoAlta: 'muitoAlta',
  },
  acidez: {
    naoInformado: 'naoInformado',
    muitoBaixa: 'muitoBaixa',
    baixa: 'baixa',
    media: 'media',
    alta: 'alta',
    muitoAlta: 'muitoAlta',
  },
  riscoErosao: {
    naoInformado: 'naoInformado',
    baixo: 'baixo',
    moderado: 'moderado',
    alto: 'alto',
    muitoAlto: 'muitoAlto',
  },
  riscoCompactacao: {
    naoInformado: 'naoInformado',
    baixo: 'baixo',
    moderado: 'moderado',
    alto: 'alto',
    muitoAlto: 'muitoAlto',
  },
  riscoEncharcamento: {
    naoInformado: 'naoInformado',
    baixo: 'baixo',
    moderado: 'moderado',
    alto: 'alto',
    muitoAlto: 'muitoAlto',
  },
  aptidaoAgricola: {
    naoInformado: 'naoInformado',
    muitoBaixa: 'muitoBaixa',
    baixa: 'baixa',
    media: 'media',
    alta: 'alta',
    muitoAlta: 'muitoAlta',
  },
  aptidaoPastagem: {
    naoInformado: 'naoInformado',
    muitoBaixa: 'muitoBaixa',
    baixa: 'baixa',
    media: 'media',
    alta: 'alta',
    muitoAlta: 'muitoAlta',
  },
  aptidaoFlorestal: {
    naoInformado: 'naoInformado',
    muitoBaixa: 'muitoBaixa',
    baixa: 'baixa',
    media: 'media',
    alta: 'alta',
    muitoAlta: 'muitoAlta',
  },
};
