export const fornecedorEnumerators = {
  tipoPessoa: {
    fisica: 'fisica',
    juridica: 'juridica',
  },
  categorias: {
    eletrica: 'eletrica',
    hidraulica: 'hidraulica',
    pintura: 'pintura',
    limpeza: 'limpeza',
    chaveiro: 'chaveiro',
    seguranca: 'seguranca',
    jardinagem: 'jardinagem',
    obra: 'obra',
    vistoria: 'vistoria',
    fotografia: 'fotografia',
    documentacao: 'documentacao',
    outro: 'outro',
  },
  uf: {
    AC: 'AC',
    AL: 'AL',
    AP: 'AP',
    AM: 'AM',
    BA: 'BA',
    CE: 'CE',
    DF: 'DF',
    ES: 'ES',
    GO: 'GO',
    MA: 'MA',
    MT: 'MT',
    MS: 'MS',
    MG: 'MG',
    PA: 'PA',
    PB: 'PB',
    PR: 'PR',
    PE: 'PE',
    PI: 'PI',
    RJ: 'RJ',
    RN: 'RN',
    RS: 'RS',
    RO: 'RO',
    RR: 'RR',
    SC: 'SC',
    SP: 'SP',
    SE: 'SE',
    TO: 'TO',
  },
};
