export const leadEnumerators = {
  origem: {
    site: 'site',
    portal: 'portal',
    instagram: 'instagram',
    facebook: 'facebook',
    google: 'google',
    whatsapp: 'whatsapp',
    telefone: 'telefone',
    placa: 'placa',
    indicacao: 'indicacao',
    evento: 'evento',
    outro: 'outro',
  },
  status: {
    novo: 'novo',
    tentativa_contato: 'tentativa_contato',
    qualificado: 'qualificado',
    visita_agendada: 'visita_agendada',
    proposta: 'proposta',
    convertido: 'convertido',
    perdido: 'perdido',
    descartado: 'descartado',
  },
  temperatura: {
    frio: 'frio',
    morno: 'morno',
    quente: 'quente',
  },
  finalidade: {
    comprar: 'comprar',
    alugar: 'alugar',
    vender: 'vender',
    anunciar: 'anunciar',
    investir: 'investir',
    avaliar: 'avaliar',
    outro: 'outro',
  },
};
