export const solicitacaoManutencaoEnumerators = {
  origem: {
    locatario: 'locatario',
    proprietario: 'proprietario',
    vistoria: 'vistoria',
    corretor: 'corretor',
    condominio: 'condominio',
    imobiliaria: 'imobiliaria',
    outro: 'outro',
  },
  categoria: {
    eletrica: 'eletrica',
    hidraulica: 'hidraulica',
    estrutura: 'estrutura',
    pintura: 'pintura',
    limpeza: 'limpeza',
    seguranca: 'seguranca',
    eletrodomestico: 'eletrodomestico',
    infiltracao: 'infiltracao',
    pragas: 'pragas',
    jardinagem: 'jardinagem',
    outro: 'outro',
  },
  prioridade: {
    baixa: 'baixa',
    media: 'media',
    alta: 'alta',
    emergencial: 'emergencial',
  },
  status: {
    aberta: 'aberta',
    em_analise: 'em_analise',
    aguardando_autorizacao: 'aguardando_autorizacao',
    autorizada: 'autorizada',
    em_execucao: 'em_execucao',
    concluida: 'concluida',
    cancelada: 'cancelada',
  },
  responsabilidadeCusto: {
    proprietario: 'proprietario',
    locatario: 'locatario',
    condominio: 'condominio',
    imobiliaria: 'imobiliaria',
    seguradora: 'seguradora',
    a_definir: 'a_definir',
  },
};
