export const imovelEnumerators = {
  tipo: {
    apartamento: 'apartamento',
    casa: 'casa',
    sobrado: 'sobrado',
    terreno: 'terreno',
    sala_comercial: 'sala_comercial',
    loja: 'loja',
    galpao: 'galpao',
    chacara: 'chacara',
    fazenda: 'fazenda',
    predio: 'predio',
    kitnet: 'kitnet',
    studio: 'studio',
    cobertura: 'cobertura',
    outro: 'outro',
  },
  finalidade: {
    venda: 'venda',
    locacao: 'locacao',
    temporada: 'temporada',
  },
  status: {
    rascunho: 'rascunho',
    em_captacao: 'em_captacao',
    disponivel: 'disponivel',
    reservado: 'reservado',
    em_negociacao: 'em_negociacao',
    vendido: 'vendido',
    locado: 'locado',
    indisponivel: 'indisponivel',
    arquivado: 'arquivado',
  },
  moeda: {
    BRL: 'BRL',
    PYG: 'PYG',
    USD: 'USD',
    EUR: 'EUR',
  },
  uf: {
    AC: 'AC',
    AL: 'AL',
    AP: 'AP',
    AM: 'AM',
    BA: 'BA',
    CE: 'CE',
    DF: 'DF',
    ES: 'ES',
    GO: 'GO',
    MA: 'MA',
    MT: 'MT',
    MS: 'MS',
    MG: 'MG',
    PA: 'PA',
    PB: 'PB',
    PR: 'PR',
    PE: 'PE',
    PI: 'PI',
    RJ: 'RJ',
    RN: 'RN',
    RS: 'RS',
    RO: 'RO',
    RR: 'RR',
    SC: 'SC',
    SP: 'SP',
    SE: 'SE',
    TO: 'TO',
  },
  mobiliado: {
    nao: 'nao',
    parcial: 'parcial',
    sim: 'sim',
  },
  ocupacao: {
    vazio: 'vazio',
    proprietario: 'proprietario',
    inquilino: 'inquilino',
    terceiro: 'terceiro',
    em_obra: 'em_obra',
  },
  riscoSeca: {
    naoInformado: 'naoInformado',
    baixo: 'baixo',
    moderado: 'moderado',
    alto: 'alto',
    muitoAlto: 'muitoAlto',
  },
  aptidaoAgricolaSolo: {
    naoInformado: 'naoInformado',
    muitoBaixa: 'muitoBaixa',
    baixa: 'baixa',
    media: 'media',
    alta: 'alta',
    muitoAlta: 'muitoAlta',
  },
  nivelDesenvolvimento: {
    naoInformado: 'naoInformado',
    naoDesenvolvida: 'naoDesenvolvida',
    parcialmenteDesenvolvida: 'parcialmenteDesenvolvida',
    desenvolvida: 'desenvolvida',
    totalmenteDesenvolvida: 'totalmenteDesenvolvida',
  },
};
